### ISSUE TITLE
Cannot compile Gentoo Linux 64 w/gcc 4.6.3, Qt 5.0

### ISSUE THREAD

**Issue by Statixcinder** [svalaskevicius/qtjs-generator#1]
Hello!

I'm having troubles compiling the generated bindings with a 'ClassInfo is not a template' error immediately on QTypeInfo_void.cpp.

Is there a suggested compile environment for the qtjs-generator that you can elaborate on? I've been long awaiting the v8 version of the qtscriptgenerator :) 

I used to hijack the internal QScriptEngine in QDeclarativeView (Qt4.0) and insert the qt bindings so I'm trying to recreate the same with Qt5 and QJSEngine

**Comment by svalaskevicius** [comment]
Hi Statixcinder,

ClassInfo is defined in the (extended) vu8 library, which is referenced in the lib directory as a git submodule (I've also noticed the commit was referencing to a missing rev., which is now fixed).

Could you maybe execute the following commands:

```
git submodule init
git submodule update
```

Also, please note that the state of this project is pre-alpha and there are many things that don't work quite right yet. I am also considering another alternative where the integration is solely based on the cpgf c++ reflection library - please see the feature/cpgf branch (again, a spike solution to see which approach is easier / more robust).

I will also update the Readme file to include the "pre-alpha" warning :)

Thanks for trying it though and please feel free to join me in making it work.

As for GCC version - I am using v. 4.7.2 as there are/were some C++11 features used.

Regards,
Sarunas

**Comment by Statixcinder** [comment]
Fixing the missing rev seems to have fixed the issue, I did notice that the generated QBasicMutex tries to use QBasicMutex( const QBasicMutex&) which is forced deleted in the qt sources, I commented that out and it finishes compile.

The test references point.x() and fails, but point.x works. Now I'm trying to come up with a way of modularizing it like the qtscriptgenerator plugins were so I can load it into QML contexts.

**Comment by svalaskevicius** [comment]
Glad to hear it worked!

As for the issues regarding the qt signal handlers (QPoint API instability) - it is using QVariant based conversion to pass it to JS - https://github.com/svalaskevicius/qtjs-generator/blob/master/bindings/QtSignalConnector.cpp . This approach is not correct as it leads to a different API than in the non-signal handler JS code.

The solution I had in mind for this, was to use a similar logic for the type detection as in the QVariant class, however, instead of using toScriptValue method it would need to invoke the custom bound Qt API from the generated sources - which leads to reworking the reflection and API binding not to use inheritance but rather an aggregation based C++ reflection (so that it could get an instance of raw Qt object and wrap it for V8).

This is the main reason why I started looking to the cpfg framework I mentioned earlier as it would potentially reduce the work required to achieve this.

The modularisation should be relatively straightforward, the difference being that the library plugins would only execute the bindApi function and would only bind their own modules.

Please let me know if you find any other difficulties or see a better approach to solving the problem above :)

Cheers,
Sarunas

**Comment by Statixcinder** [comment]
I'm curious why the original qscriptgenerator methodology isn't sufficient for binding to v8 (I need to port my old conversion from IDL -> QtScript to IDL -> v8). I've also noticed the compiled form of 'test' is 84M now whereas the old QtScript generated bindings were just a few MB -- I suppose this is due to generating objects for each class vs a collectively compiled single-source object per module which would affect both the vu8 and cpfg version?

I think the closer the bindings are to the 4.7 version will generate more acceptance of using the new generator for whichever underlying implementation is chosen, right now the implementations of enums is tedious (qt.QFlags_QIODevice_OpenModeFlag_ vs QFlags.QIODevice.OpenModeFlag) which I figure is just a 'to be done' case :)

Keep up the excellent work, I think you are the only person tackling this crazy problem, but the final result will be awesome for Qt users!

**Comment by svalaskevicius** [comment]
qscriptgenerator is heavily relying on QtScript which sadly won't support V8.. (there has been a spike for that by the Qt team and it was cancelled AFAIK)

As for the size of the compiled binaries - thats something I track as well (after I noticed it generated 500Mb executable file :) - most of that being debug info)

As for the ugly API - yes, it was a quick and dirty hack to make C++ operators like Template < Class::Class >  appear in Js syntax. This will be dealt with as soon as the javascript code is operational.

Cheers! The main motivator of this is http://github.com/svalaskevicius/ionpulse , which will benefit from a faster JS engine as well :)

**Comment by svalaskevicius** [comment]
Hi there,

I've switched to cpgf completely and already believe this is the way to go forward.
Also, in addition to to V8, it provides Lua and Python bindings OOTB (which I haven't tried).

Only QtCore is enabled yet, however, the basic example is working correctly now:
https://github.com/svalaskevicius/qtjs-generator/blob/master/examples/basic.js

Please see https://github.com/svalaskevicius/qtjs-generator/blob/master/metagen/config.js for the info of what functionality is skipped (I'll refactor this config once I have a free minute :) ).

As for the file size, w/o debug info and with -Os, it generates ~30Mb for the qtCore bindings.. which is not ideal in any way, but might be acceptable in most cases - what do you think? (upx manages to compress the executable to only several Mb, but its not a good idea for a shared library)

Kind Regards,
Sarunas

**Comment by Statixcinder** [comment]
Currently in Qt5 there doesn't seem to be an 'easy conversion mechanism' like the old qScriptRegisterMetaType macro where you could provide a 'toScriptValue' and 'fromScriptValue' implementation in regards to a QJSEngine, have you managed to find a way to do that in V8 with the generator? This prevents conversion for POD types see http://qt-project.org/forums/viewthread/24931 with a Qt bug report showing up that is unreviewed :(

**Comment by svalaskevicius** [comment]
Not really, I didn't spend too much time on that side yet :) and also there is no compatibility with QML Js types yet..

However, C++ metadata can be described using http://www.cpgf.org/document/reflection-build-meta-data.html . Also, it could be automated by inspecting QObject metadata and passing it to cpgf (POD types would have to be manually described using cgpf or generated using doxygen).

Some update on the progress - I've finally managed to open the QMainWindow using cpgf, also with an attached Qt slot callback (feature/qtWidgets branch) :)

**Comment by svalaskevicius** [comment]
The generated code compiles well and both qtCore and qtWidgets work as expected. I've added a separate ticket #3 for integration with QML.
