### ISSUE TITLE
'QT_LARGEFILE_SUPPORT' was not declared in this scope

### ISSUE THREAD

**Issue by ericmayc** [svalaskevicius/qtjs-generator#19]
Hi @svalaskevicius , 

I compile android version for qtjs, there is an error, can you help to resolve?

D:\Qt\android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -c -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -std=gnu++0x -Wno-unused-parameter -DBUILDING_DLL -g -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIC -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -ID:\Qt\Qt5.3.0\5.3\android_armv7\mkspecs\android-g++ -I......\qtjs-generator\src\core -I......\qtjs-generator\lib\cpgf\include -I......\qtjs-generator\metagen\build\QtCore\include -I......\qtjs-generator\metagen\build\QtWidgets\include -I......\qtjs-generator\metagen\build\QtQml\include -I......\qtjs-generator\metagen\build\QtGui\include -I......\qtjs-generator\include -I......\qtjs-generator\lib\node\deps\v8\include -I......\qtjs-generator\metagen\build -ID:\Qt\Qt5.3.0\5.3\android_armv7\include -ID:\Qt\Qt5.3.0\5.3\android_armv7\include\QtGui -ID:\Qt\Qt5.3.0\5.3\android_armv7\include\QtCore -ID:/work/testcode/build-qtjs-Android_for_armeabi_v7a_GCC_4_8_Qt_5_3_0-Debug/src/core -ID:\Qt\android-ndk-r9c\sources\cxx-stl\gnu-libstdc++\4.8\include -ID:\Qt\android-ndk-r9c\sources\cxx-stl\gnu-libstdc++\4.8\libs\armeabi-v7a\include -ID:\Qt\android-ndk-r9c\platforms\android-9\arch-arm\usr\include -I. -o meta_qtcore_qconfig.obj ......\qtjs-generator\metagen\build\QtCore\src\meta_qtcore_qconfig.cpp
In file included from ......\qtjs-generator\metagen\build\QtCore\src\meta_qtcore_qconfig.cpp:47:0:
......\qtjs-generator\metagen\build\QtCore\include/meta_qtcore_qconfig.h: In function 'void qt_metadata::buildMetaClass_Global_qconfig(D)':
......\qtjs-generator\metagen\build\QtCore\include/meta_qtcore_qconfig.h:28:43: error: 'QT_LARGEFILE_SUPPORT' was not declared in this scope
         ._element("QT_LARGEFILE_SUPPORT", QT_LARGEFILE_SUPPORT)
                                           ^
Makefile:10078: recipe for target 'meta_qtcore_qconfig.obj' failed
mingw32-make[1]: **\* [meta_qtcore_qconfig.obj] Error 1

**Comment by svalaskevicius** [comment]
Hi,

The committed bindings were generated on Linux so it had it available.. But
some functionality is not available on android..

you can disable some bindings by editing the config (qtCore.js) in metagen
directory and running the metagen again.

Let me know if you need any help/examples with configuring the metagen :)

**Comment by ericmayc** [comment]
Do you mean I disable this file in qtCore.js? can you give me the example for fixing this one? I will be appreciate it.

There is another questions.
First, why qtjs depends on V8? I move V8 location and compile qtjs, there is a error occurs"**\* No rule to make target '......\qtjs-generator\lib\node\deps\v8\include\v8.h', needed by 'meta_qtcore_qalgorithms.obj'.  Stop".

Second, in the example, you write a class named WaveAngleClass and it is inherited by Waveangle. I want to know which engine analyze WaveAngleClass, V8 from node or V4 from qml engine? In other words, what is the relationship between V8 from node and V4 from qml?

**Comment by ericmayc** [comment]
I want to confirm If I don't use API of QtCore and GUI in JS，I needn't to generate meta data for these two moudles, right?

**Comment by svalaskevicius** [comment]
If you add `QT_LARGEFILE_SUPPORT` to the config the same way as e.g. `QT_EDITION` in 
https://github.com/svalaskevicius/qtjs-generator/blob/master/metagen/qtCore_cfg.js#L173

the metagen will skip it from the build :) [see "Updating Qt bindings" step in the Readme.md]

## 

as for `WaveAngleClass` and `Waveangle` -  `WaveAngleClass`  is purely V8 object, Qml doesn't know about it and cannot access it, `Waveangle` in the other hand, is purely Qml object (V4) and V8 doesn't know about it. They're both connected using https://github.com/svalaskevicius/qtjs-generator/blob/master/src/runner/dynamicQObject.h

## 

As for the required modules - you could skip some, that you don't plan to use, e.g. Widgets module, however the Core module will still be required if you want to do basic Qt stuff in Js.

## 

As for the summary - qtjs binds Qt to V8 js engine, where node is available as well - from qml's js perspective its the same as C++ code (just that its in js :) ) and the usual c++ code <-> Qml semantics still apply.

**Comment by ericmayc** [comment]
thank you so much!
I have compiled a linux version, it runs examples well!
Then I try to skip Core module, it runs examples failed. As you said, the Core module is the basic.
I am compiling android version. There are many problems, that is why I want to skip this moudle.
Thanks again! And I will need your more help on compiling android version.
