### ISSUE TITLE
metagen generate data failed

### ISSUE THREAD

**Issue by ericmayc** [svalaskevicius/qtjs-generator#20]
Preprocessing /home/eric/work/qtjs-generator-metagen/metagen/qtheaders/qtbase/tests/auto/corelib/xml/qxmlstream/XML-Test-Suite/xmlconf/japanese/pr-xml-utf-16.xml...
error: /home/eric/work/qtjs-generator-metagen/metagen/qtheaders/qtbase/tests/auto/corelib/xml/qxmlstream/XML-Test-Suite/xmlconf/japanese/pr-xml-utf-16.xml: failed to translate characters from UCS-2 to UTF-8: check INPUT_ENCODING
Exiting...

**Comment by ericmayc** [comment]
I user command "./generate_bindings.sh Qt5.3.0/5.3/Src", is it right?
I think it is wrong dir. After I read the file generate_bindings.sh, I think maybe I should use command "./generate_bindings.sh Qt5.3.0/5.3/android_armv7".

**Comment by svalaskevicius** [comment]
Ah right. I remember qt had different directory structure in other OS'es.

As the current generator is written for linux pkg structure - can you maybe
check if it's possible to use those headers for the first generator
phase?

**Comment by ericmayc** [comment]
Maye you should state it in metagen instructions.

**Comment by svalaskevicius** [comment]
You're right - will do it this evening :)

Thanks!
