### ISSUE TITLE
error: conversion from 'wchar_t' to 'QJsonValue' is ambiguous

### ISSUE THREAD

**Issue by ericmayc** [svalaskevicius/qtjs-generator#21]
Hi @svalaskevicius ,

I compile on android, error occurs. I confused that why it can access private method. How should solve this problem? Can you help to investigate it ?

/home/eric/QtAndroid/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -c -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -std=gnu++0x -Wno-unused-parameter -DBUILDING_DLL -g -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIC -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/home/eric/Qt5.3.0/5.3/android_armv7/mkspecs/android-g++ -I../../../src/core -I../../../lib/cpgf/include -I../../../metagen/build/QtCore/include -I../../../metagen/build/QtWidgets/include -I../../../metagen/build/QtQml/include -I../../../metagen/build/QtGui/include -I../../../include -I../../../lib/node/deps/v8/include -I../../../metagen/build -I/home/eric/Qt5.3.0/5.3/android_armv7/include -I/home/eric/Qt5.3.0/5.3/android_armv7/include/QtGui -I/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore -I/home/eric/work/qtjs-generator/build/src/core -I/home/eric/QtAndroid/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include -I/home/eric/QtAndroid/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include -I/home/eric/QtAndroid/android-ndk-r9d/platforms/android-9/arch-arm/usr/include -I. -o meta_qtcore_qjsonarray.o ../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp
In file included from ../../../lib/cpgf/include/cpgf/gmetacommon.h:4:0,
                 from ../../../lib/cpgf/include/cpgf/private/gmetaannotation_p.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetaannotation.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetadefine.h:4,
                 from ../../../include/./qt_cpgf_compat.h:5,
                 from ../../../include/qtCore_cpgf_compat.h:3,
                 from ../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp:3:
../../../lib/cpgf/include/cpgf/gtypetraits.h: In instantiation of 'const bool cpgf::IsConvertible<wchar_t, QJsonValue, void>::Result':
../../../lib/cpgf/include/cpgf/genableif.h:57:2:   required from 'const bool cpgf::GOrResult<cpgf::IsConvertible<wchar_t, QJsonValue, void>, cpgf::GAndResultcpgf::IsEnum<wchar_t, cpgf::IsConvertible<int, QJsonValue, void>, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult>, cpgf::GAndResultcpgf::IsEnum<QJsonValue, cpgf::IsConvertible<wchar_t, int, void>, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult>, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult>::Result'
../../../lib/cpgf/include/cpgf/genableif.h:19:8:   required from 'struct cpgf::GEnableIfResult<cpgf::GOrResult<cpgf::IsConvertible<wchar_t, QJsonValue, void>, cpgf::GAndResultcpgf::IsEnum<wchar_t, cpgf::IsConvertible<int, QJsonValue, void>, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult>, cpgf::GAndResultcpgf::IsEnum<QJsonValue, cpgf::IsConvertible<wchar_t, int, void>, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult, cpgf::GTrueResult>, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult, cpgf::GFalseResult>, void>'
../../../lib/cpgf/include/cpgf/private/gvariant_p.h:126:41:   required from 'static To cpgf::variant_internal::CastVariantHelper<From, To, Enabled>::cast(const From&) [with From = wchar_t; To = QJsonValue; Enabled = void]'
../../../lib/cpgf/include/cpgf/private/gvariant_p.h:735:97:   required from 'static cpgf::variant_internal::CastFromVariant<T, Policy>::ResultType cpgf::variant_internal::CastFromVariant<T, Policy>::cast(const cpgf::GVariant&) [with T = const QJsonValue&; Policy = cpgf::VarantCastCopyConstRef; cpgf::variant_internal::CastFromVariant<T, Policy>::ResultType = QJsonValue]'
../../../lib/cpgf/include/cpgf/gvariant.h:218:99:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
../../../lib/cpgf/include/cpgf/private/gmetaoperator_p.h:443:19:   required from 'static cpgf::GVariant cpgf::meta_internal::GMetaOperatorData<OT, Op, Signature, Policy, typename cpgf::GEnableIfResult<cpgf::meta_internal::IsBinaryOperator<Op> >::Result>::virtualInvoke2(const cpgf::GVariant&, const cpgf::GVariant&) [with OT = QJsonArray; cpgf::GMetaOpType Op = (cpgf::GMetaOpType)1u; Signature = QJsonArray (_)(const cpgf::GMetaSelf&, const QJsonValue&); Policy = cpgf::MakePolicycpgf::GMetaRuleCopyConstReference<1 >]'
../../../lib/cpgf/include/cpgf/private/gmetaoperator_p.h:473:4:   required from 'cpgf::meta_internal::GMetaOperatorData<OT, Op, Signature, Policy, typename cpgf::GEnableIfResult<cpgf::meta_internal::IsBinaryOperator<Op> >::Result>::GMetaOperatorData() [with OT = QJsonArray; cpgf::GMetaOpType Op = (cpgf::GMetaOpType)1u; Signature = QJsonArray (_)(const cpgf::GMetaSelf&, const QJsonValue&); Policy = cpgf::MakePolicycpgf::GMetaRuleCopyConstReference<1 >; typename cpgf::GEnableIfResultcpgf::meta_internal::IsBinaryOperator<Op >::Result = void]'
../../../lib/cpgf/include/cpgf/private/gmetaoperator_p.h:843:59:   required from 'cpgf::meta_internal::GMetaOperatorDataBase\* cpgf::meta_internal::GMetaOperatorCreator<Op>::create(const Policy&) const [with OT = QJsonArray; Signature = QJsonArray (_)(const cpgf::GMetaSelf&, const QJsonValue&); Policy = cpgf::MakePolicycpgf::GMetaRuleCopyConstReference<1 >; cpgf::GMetaOpType Op = (cpgf::GMetaOpType)1u]'
../../../lib/cpgf/include/cpgf/gmetadefine.h:310:3:   required from 'cpgf::GDefineMetaOperator<DerivedType> cpgf::GDefineMetaCommon<ClassType, DerivedType>::_operator(const Creator&, const Policy&) [with FT = QJsonArray (_)(const cpgf::GMetaSelf&, const QJsonValue&); Creator = cpgf::meta_internal::GMetaOperatorCreator<(cpgf::GMetaOpType)1u>; Policy = cpgf::MakePolicycpgf::GMetaRuleCopyConstReference<1 >; ClassT = QJsonArray; DerivedType = cpgf::GDefineMetaClass<QJsonArray>]'
../../../metagen/build/QtCore/include/meta_qtcore_qjsonarray.h:230:5:   required from 'void qt_metadata::buildMetaClass_QJsonArray(D) [with D = cpgf::GDefineMetaClass<QJsonArray>]'
../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp:72:126:   required from here
../../../lib/cpgf/include/cpgf/gtypetraits.h:503:2: error: conversion from 'wchar_t' to 'QJsonValue' is ambiguous
  G_STATIC_CONSTANT(bool, Result = (IsSameType<From, To>::Result || (sizeof(check(from)) == sizeof(typetraits_internal::YesType))));
  ^
In file included from ../../../lib/cpgf/include/cpgf/gvartypedata.h:7:0,
                 from ../../../lib/cpgf/include/cpgf/gvariant.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetacommon.h:6,
                 from ../../../lib/cpgf/include/cpgf/private/gmetaannotation_p.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetaannotation.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetadefine.h:4,
                 from ../../../include/./qt_cpgf_compat.h:5,
                 from ../../../include/qtCore_cpgf_compat.h:3,
                 from ../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp:3:
../../../lib/cpgf/include/cpgf/gtypetraits.h:500:14: note: candidates are:
  static From from;
              ^
In file included from /home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsondocument.h:45:0,
                 from /home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/QJsonDocument:1,
                 from ../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp:24:
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:123:12: note: QJsonValue::QJsonValue(const void_) <near match>
     inline QJsonValue(const void *) {}
            ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:123:12: note:   no known conversion for argument 1 from 'wchar_t' to 'const void_'
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:86:31: note: QJsonValue::QJsonValue(const char_) <near match>
     inline QT_ASCII_CAST_WARN QJsonValue(const char *s)
                               ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:86:31: note:   no known conversion for argument 1 from 'wchar_t' to 'const char_'
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:82:5: note: QJsonValue::QJsonValue(qint64)
     QJsonValue(qint64 n);
     ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:81:5: note: QJsonValue::QJsonValue(int)
     QJsonValue(int n);
     ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:80:5: note: QJsonValue::QJsonValue(double)
     QJsonValue(double n);
     ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:79:5: note: QJsonValue::QJsonValue(bool)
     QJsonValue(bool b);
     ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:78:5: note: QJsonValue::QJsonValue(QJsonValue::Type) <near match>
     QJsonValue(Type = Null);
     ^
/home/eric/Qt5.3.0/5.3/android_armv7/include/QtCore/qjsonvalue.h:78:5: note:   no known conversion for argument 1 from 'wchar_t' to 'QJsonValue::Type'
In file included from ../../../lib/cpgf/include/cpgf/gvartypedata.h:7:0,
                 from ../../../lib/cpgf/include/cpgf/gvariant.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetacommon.h:6,
                 from ../../../lib/cpgf/include/cpgf/private/gmetaannotation_p.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetaannotation.h:4,
                 from ../../../lib/cpgf/include/cpgf/gmetadefine.h:4,
                 from ../../../include/./qt_cpgf_compat.h:5,
                 from ../../../include/qtCore_cpgf_compat.h:3,
                 from ../../../metagen/build/QtCore/src/meta_qtcore_qjsonarray.cpp:3:
../../../lib/cpgf/include/cpgf/gtypetraits.h:498:38: error:   initializing argument 1 of 'static cpgf::typetraits_internal::YesType cpgf::IsConvertible<From, To, Enabled>::check(To) [with From = wchar_t; To = QJsonValue; Enabled = void; cpgf::typetraits_internal::YesType = char]'
  static typetraits_internal::YesType check(To);
                                      ^

**Comment by ericmayc** [comment]
I modified the qCore_cpgf_compat.h, added one line "IsSameType<From, wchar_t>,",  now it can compiled pass, but I don't know if it is right.

template <typename From>
struct IsConvertible < From, ::QJsonValue, typename GEnableIfResult <
        GOrResult <
        IsSameType<From, unsigned int>,
        IsSameType<From, long signed int>,
        IsSameType<From, long unsigned int>,
        IsSameType<From, long long signed int>,
        IsSameType<From, long long unsigned int>,
        IsSameType<From, long double>,
        IsSameType<From, wchar_t>,
        IsPointer<From>
        >
        >::Result
        > {
    G_STATIC_CONSTANT(bool, Result = false);
};

**Comment by svalaskevicius** [comment]
yeah this looks right (except github removing the bits from your pasted code :) ) as that will just tell cpgf not to try to convert wchar_t to QJsonValue as it doesnt have such constructor.. 

would you be able to make a PR for this? :)

Thanks!

**Comment by ericmayc** [comment]
I am new man. what is PR?

**Comment by svalaskevicius** [comment]
Sorry, a pull request :)

As you mentioned you've fixed the issue already it should take just a few
clicks in github for your fix to be available for everyone :)

**Comment by ericmayc** [comment]
But this problem just for android. On Linux, it works well.

**Comment by svalaskevicius** [comment]
The fix should be harmless wherever wchar_t is available. But yeah we
should check if linux build doesn't break :)

If linux build breaks I'll try to find a generic fix based on yours :)

**Comment by ericmayc** [comment]
the linux version is ok. I can run examples.

**Comment by ericmayc** [comment]
There is another problem. It occurs in a wrapper class which can not access the parent class, but I compare it to other wrapper classes, there is no different. Can you give me some tips?

In file included from ......\metagen\build\QtGui\src\meta_qtgui_qopengltimerquery.cpp:12:0:
......\metagen\build\QtGui\include/meta_qtgui_qopengltimerquery.h:55:60: error: expected class-name before ',' token
 class QOpenGLTimeMonitorWrapper : public QOpenGLTimeMonitor, public cpgf::GScriptWrapper {
...
In file included from ......\metagen\build\QtGui\src\meta_qtgui_qopengltimerquery.cpp:12:0:
......\metagen\build\QtGui\include/meta_qtgui_qopengltimerquery.h: In member function 'int qt_metadata::QOpenGLTimeMonitorWrapper::qt_metacall(QMetaObject::Call, int, void**)':
......\metagen\build\QtGui\include/meta_qtgui_qopengltimerquery.h:204:16: error: 'QOpenGLTimeMonitor' has not been declared
         return QOpenGLTimeMonitor::qt_metacall(__arg0, __arg1, __arg2);

...
In file included from ......\include/./qt_cpgf_compat.h:5:0,
                 from ......\include/./qtCore_cpgf_compat.h:3,
                 from ......\include/qtGui_cpgf_compat.h:3,
                 from ......\metagen\build\QtGui\src\meta_qtgui_qopengltimerquery.cpp:3:
......\lib\cpgf\include/cpgf/gmetadefine.h: In instantiation of 'cpgf::GDefineMetaInnerClass<DerivedType> cpgf::GDefineMetaCommon<ClassType, DerivedType>::_class(MetaClass) [with MetaClass = int; ClassT = void; DerivedType = cpgf::GDefineMetaDangle<void>]':
......\metagen\build\QtGui\src\meta_qtgui_qopengltimerquery.cpp:27:22:   required from here
......\lib\cpgf\include/cpgf/gmetadefine.h:323:48: error: request for member 'getMetaInfo' in 'defineClass', which is of non-class type 'int'
   return this->_class(defineClass.getMetaInfo());
                                                ^
......\lib\cpgf\include/cpgf/gmetadefine.h: In member function 'cpgf::GDefineMetaInnerClass<DerivedType> cpgf::GDefineMetaCommon<ClassType, DerivedType>::_class(MetaClass) [with MetaClass = int; ClassT = void; DerivedType = cpgf::GDefineMetaDangle<void>]':
......\lib\cpgf\include/cpgf/gmetadefine.h:324:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^

**Comment by svalaskevicius** [comment]
Hmm the parent class might not be available (included).

You might want to include it manually.. Or simply disable the wrapper
generation for it in qtGui config for metagen as it looks you won't need to
override it in js.

**Comment by ericmayc** [comment]
But it has been included in .cpp. I will try to disable the wrapper for it. Thanks!
About PR, I need some time. Because I am not familiar github. But I will do it.

#include <QtGui/qopengltimerquery.h>

#include "meta_qtgui_qopengltimerquery.h"

**Comment by ericmayc** [comment]
It works until I skip these two classes.

**Comment by svalaskevicius** [comment]
Awesome! I was thinking about android support earlier but never got to do
it.

Maybe it's even worth to prep an installable android package? What do you
think? Are there any features you think should be added?

I was thinking of ways to reduce the binary size.. But apart from removing
unused bindings that's going to be hard (as it's mainly due to the
instantiated cpgf templates) .. Do you think the size is a big problem?

Thanks again for your hard work!

**Comment by ericmayc** [comment]
Now I compiling runner, so many problems there. I am struggling.

**Comment by svalaskevicius** [comment]
Could you paste some errors?

There is jit used in the runner so it might be the cause of the errors - if
this is the case we can remove jit and replace with precompiled
placeholders..

**Comment by ericmayc** [comment]
It my own problems, because I don't use V8 and node you support. I do some changes on node and use a higher version V8.

**Comment by ericmayc** [comment]
Maybe you can remove widgets and most parts of gui for android, because the size is a big problem. If you can supply a more flexible platform. For example, qtjs just is a platform, users can develop apps with JS and package .apk and deploy.

**Comment by ericmayc** [comment]
If you can supply precompiled v8 and others modules depended, it is easier to use.

**Comment by svalaskevicius** [comment]
Thanks!

Re excluding unneeded modules - I was thinking about this and that's the
main reason for creating them as dynamic libraries - of course a bit of
work is left to make them as proper plugins, loaded at runtime...

You could skip the widgets library now by modifying two project files - the
main one to remove from the recursively built libs and the project include
file to remove the linked libs.. (might also need to remove one source line
where runner initialises it as it's not yet loaded dynamically (as a plugin) ).

As for distributing the precompiled libs - maybe it's better to precompile
the full binaries for major platforms? But then there is no way to remove
unwanted bindings...

**Comment by wqking** [comment]
Is V8 a mandatory requirement?
I know the purpose of qtjs is to bind Qt to V8, but it would be nice if the project is decoupled from V8, thus the users can use arbitrary script engines supported by cpgf.

**Comment by svalaskevicius** [comment]
That's a good question :) originally I have only targeted v8+nodejs.. There
are some functions in the runner that assume v8.. But it could be switched
to another engine relatively easily (although I haven't tried that :)) -
the main work (bindings themselves) are purely cpgf.
